<?php

$en = [
    'title' => 'Invest in Nature\'s Growth | Treevest',
    'explore_farms' => 'Explore Farms',
    'dashboard' => 'Dashboard',
    'log_in' => 'Log in',
    'start_investing' => 'Start Investing',
    'hero_badge' => 'Now open for Durian & Mango investments',
    'hero_title' => 'Invest in roots.',
    'hero_title_highlight' => 'Harvest returns.',
    'hero_desc' => 'Back verified agricultural farms by investing in individual fruit trees. Track their growth, and earn returns based on actual harvests. A tangible asset for your portfolio.',
    'view_available_trees' => 'View Available Trees',
    'how_it_works' => 'How it works',
    'expected_roi' => 'Expected ROI',
    'expected_roi_val' => '12% - 18%',
    'expected_roi_unit' => '/ yr',
    'backed_by' => 'Backed by',
    'real_assets' => 'Real Assets',
    'features_title' => 'Cultivating wealth, naturally.',
    'features_desc' => 'Unlike traditional stocks, your investment grows in the soil. We connect you directly with verified farm partners.',
    'f1_title' => 'Verified Farms',
    'f1_desc' => 'Every partner farm undergoes strict KYC and site inspections before listing their crops.',
    'f2_title' => 'Track Growth',
    'f2_desc' => 'Get regular health updates, photos, and weather reports right on your dashboard.',
    'f3_title' => 'Earn Dividends',
    'f3_desc' => 'When the trees are harvested and fruits are sold, you receive your share of the profits.',
    'footer_copyright' => '© 2026 Treevest. All rights reserved.',
    'footer_disclaimer' => 'Agricultural investments carry inherent risks. Please read our risk disclosure.',
];
$id = [
    'title' => 'Investasi dalam Pertumbuhan Alam | Treevest',
    'explore_farms' => 'Jelajahi Kebun',
    'dashboard' => 'Dasbor',
    'log_in' => 'Masuk',
    'start_investing' => 'Mulai Berinvestasi',
    'hero_badge' => 'Sekarang dibuka untuk investasi Durian & Mangga',
    'hero_title' => 'Berinvestasi pada akar.',
    'hero_title_highlight' => 'Panen hasilnya.',
    'hero_desc' => 'Dukung pertanian yang terverifikasi dengan berinvestasi pada pohon buah. Lacak pertumbuhannya, dan dapatkan keuntungan berdasarkan hasil panen aktual. Aset berwujud untuk portofolio Anda.',
    'view_available_trees' => 'Lihat Pohon Tersedia',
    'how_it_works' => 'Cara kerjanya',
    'expected_roi' => 'Estimasi ROI',
    'expected_roi_val' => '12% - 18%',
    'expected_roi_unit' => '/ thn',
    'backed_by' => 'Didukung oleh',
    'real_assets' => 'Aset Nyata',
    'features_title' => 'Menumbuhkan kekayaan, secara alami.',
    'features_desc' => 'Tidak seperti saham tradisional, investasi Anda tumbuh di tanah. Kami menghubungkan Anda secara langsung dengan mitra petani yang terverifikasi.',
    'f1_title' => 'Kebun Terverifikasi',
    'f1_desc' => 'Setiap mitra kebun menjalani KYC ketat dan inspeksi lokasi sebelum mendaftarkan tanaman mereka.',
    'f2_title' => 'Lacak Pertumbuhan',
    'f2_desc' => 'Dapatkan pembaruan kesehatan berkala, foto, dan laporan cuaca langsung di dasbor Anda.',
    'f3_title' => 'Dapatkan Dividen',
    'f3_desc' => 'Ketika pohon dipanen dan buah dijual, Anda menerima bagian keuntungan Anda.',
    'footer_copyright' => '© 2026 Treevest. Hak cipta dilindungi undang-undang.',
    'footer_disclaimer' => 'Investasi pertanian memiliki risiko bawaan. Silakan baca pengungkapan risiko kami.',
];
file_put_contents('public/locales/en/welcome.json', json_encode($en, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
file_put_contents('public/locales/id/welcome.json', json_encode($id, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES));
